config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'products', to: 'products#index'
  resources :categories
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories do
  resources :products
  end
  
  get 'cart', to: 'welcome#cart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_attached_file :avatar, styles: { large: "1200x620>", medium: "500x300#", small: "200x200#", thumb: "80x50#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    has_many :products, dependent: :destroy
    validates :name, presence: true, length: { minimum: 3, maximum: 20}
    validates :feature, presence: true, length: { minimum: 3, maximum: 30}
    validates :model, presence: true

end
    

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  
    validates :name, presence: true, length: { minimum: 3, maximum: 50}
    validates :description, presence: true, length: { minimum: 10, maximum: 300}
    validates :price, presence: true
    validates :make, presence: true, length: { minimum: 4, maximum: 4}
    
    has_attached_file :picture, styles: { large: "1200x620>", medium: "500x300#", small: "200x200#", thumb: "80x50#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    
    validates :username, presence: true, 
        uniqueness: { case_sensitive: false}, 
        length: {minimum: 3, maximum: 25}
        
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 50},
    uniqueness: {case_sensitive:false},
    format: { with: VALID_EMAIL_REGEX }
    
    has_secure_password
end
    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

   def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

   def logged_in?
      !!current_user
   end

   def require_user
      if !logged_in?
         flash[:danger] = "You must be logged in to perform that action"
         redirect_to root_path
      end
   end
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    before_action :set_category, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def edit

    end

    def create
      #render plain: params[:product].inspect
      @category = Category.new(category_params)

      if @category.save
          flash[:notice] = "Category was successfully created"
          redirect_to category_path(@category)
      else
          render 'new'
      end
    end

    def update
      if @category.update(category_params)
        flash[:notice] = "Category was successfully updated"
        redirect_to category_path(@category)
      else
        render 'edit'
      end
    end

    def show

    end

    def destroy
      @category.destroy
      flash[:notice] = "Category was successfully deleted"
      redirect_to categories_path
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :feature, :model, :avatar)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
    def index
    @products = Product.all
    end

  def create
    @category = Category.find(params[:category_id])
    @product = Product.new(product_params)
    @product.category_id = @category.id

    unless @product.save
      flash[:alert] = @product.errors.full_messages
    end

     redirect_to category_path(@category)
  end

  def destroy
    @category = Category.find(params[:category_id])
    @product = @category.products.find(params[:id])
    @product.destroy
    redirect_to category_path(@category)
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :make, :picture)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
   
   end
   
   def create
    user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
             flash[:success] = "You have successfully logged in"
             
             redirect_to categories_path
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end 
   end
   
   def destroy
       session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update]
    
    def index 
       @users = User.all 
    end
   def new
      @user = User.new
    end
    
    def create
      @user = User.new(user_params) 
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the CamShop App #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end
    
    def edit
         
    end
    def update
       
       if @user.update(user_params)
           flash[:success] = "Your account was updated successfully"
           redirect_to categories_path
        else
           render 'edit' 
        end
    end
    
    def show
      
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def require_same_user
       if current_user != @user
           flash[:danger] = "You can only edit your own account"
           redirect_to root_path
        end
       
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   def home
       
    end
    
    
    def about
        
    end
    
    def cart
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
   <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@category.errors.count, "error") %>
            prohibited this category from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% @category.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul> 
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

  <%= form_for @category do |f| %>
  <div class="w3-container w3-card-4 w3-padding-16 w3-white form">
      <div class="w3-secton">      
        <%= f.label :name %>
        <%= f.text_field :name, class: "w3-input" %>
      </div>
     
      <div class="w3-secton">      
        <%= f.label :feature %>
        <%= f.text_area :feature, class: "w3-input" %>
      </div>
      <div class="w3-secton">      
        <%= f.label :model %>
        <%= f.text_field :model, class: "w3-input" %>
      </div>
      <div class="w3-secton">      
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: "w3-input" %>
      </div>
      <%= f.submit class: 'w3-button w3-right w3-theme w3-hover-teal' %>
      
  </div>
<% end %>

<h3 class="w3-large w3-border-teal"><%= link_to "Back to categories listing", categories_path %></h3>

app/views/categories/edit.html.erb
<div class="w3-container w3-padding-32 w3-theme-l5" id="contact">
  <div class="w3-row">
      <div class="w3-col m5">
      <div class="w3-padding-16"><h3><span class="w3-xlarge w3-border-teal w3-bottombar">Edit this category</span></h3></i></div>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<h1 align="center">Welcome!!!</h1>

<h2 align="center">Listing All categories</h2>

<% @categories.each do |category| %>

  <div class="w3-container w3-padding-32 w3-theme-l5 w3-center" id="contact">
    <div class="w3-row">
      <h3 align="center"><span class="w3-xlarge w3-border-teal w3-bottombar">Company name: <%= category.name %></span></h3>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Feature: <%= category.feature %></p>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Model: <%= category.model %></p>
      <% category.save %>
      
     </div> 
  </div>


<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    
      <tr>
        <td class="w3-large w3-border-teal "><%= link_to 'Explore our products', category_path(category) %> |</td> 
        <% if logged_in? && current_user.admin? %>
        <td class="w3-large w3-border-teal "><%= link_to 'Edit', edit_category_path(category) %> |</td> 
        <td class="w3-large w3-border-teal "><%= link_to 'Destroy',category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    
   </tbody>
</table>
<br>
  <% end %>
  <% if logged_in? && current_user.admin? %>
  <h3 align="center"><spam><%= link_to 'Add new company/category', new_category_path, class: "w3-button w3-center w3-theme w3-hover-teal w3-medium w3-theme btn w3-bar-item w3-text-white"%> </spam></h3>
  <% end %>

app/views/categories/new.html.erb
<div class="w3-container w3-padding-32 w3-theme-l5" id="contact">
  <div class="w3-row">
    <div class="w3-col m5">
      <div class="w3-padding-16"><h3><span class="w3-xlarge w3-border-teal w3-bottombar">Add a new company/category for camera's</span></h3></i></div>
    </div>
  </div>
   <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<h1 align="center">Welcome!!!</h1>

  <div class="w3-container w3-padding-32 w3-theme-l5 w3-center" id="contact">
    <div class="w3-row">
      <h3 align="center"><span class="w3-xlarge w3-border-teal w3-bottombar">Company name: <%= @category.name %></span></h3>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Feature: <%= @category.feature %></p>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Model: <%= @category.model %></p>
   <% #@category.save %>

     </div>
  </div>

      <% if @category.products.present? -%>
        <div class="w3-padding-16"><h3 align="center"><span class="w3-xlarge w3-border-teal w3-bottombar">Our Products...!!!</span></h3></i></div>
          <% @category.products.each do |product| %>
            <div class="w3-container w3-padding-32 w3-theme-l5 w3-center" id="contact">
              <div class="w3-row">
                <h3 align="center"><span class="w3-xlarge w3-border-teal w3-bottombar">Product: <%= product.name %></span></h3>
                <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Description: <%= product.description %></p>
                <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Price: <%= product.price %></p>
                <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Making Year: <%= product.make %></p>
                 <p>
                   <% if current_user.admin? %>
                    <spam><%= link_to 'Destroy Product', [product.category, product],
                     method: :delete, class: "w3-button w3-center w3-theme w3-hover-teal w3-medium w3-theme btn w3-bar-item w3-text-white",
                     data: { confirm: 'Are you sure?' } %> </spam>
                    <% end %>
                     <spam><%= link_to 'Buy Now', cart_path, class: "w3-button w3-center w3-theme w3-hover-teal w3-medium w3-theme btn w3-bar-item w3-text-white",
                     data: { confirm: 'Are you sure?' } %> </spam>

                 </p>


               </div>
            </div>
          <% end %>
        </div>
      <% end -%>

      <div class="w3-container w3-padding-32 w3-theme-l5" id="contact">
        <div class="w3-row">
          <div class="w3-col m5">
            <div class="w3-padding-16"><h3><span class="w3-xlarge w3-border-teal w3-bottombar">Add a product:</span></h3></i></div>
          </div>
        </div>
          <%= form_tag(category_products_path(@category), method: :post, local: true) do %>
            <%#= hidden_field_tag(:category_id, @category.id) %>
            <% @category.products.build -%>
            <div class="w3-container w3-card-4 w3-padding-16 w3-white form">
                <div class="w3-secton">
                  <%= label_tag :name %>
                  <spam class="w3-input"><%= text_field_tag 'product[name]'%></spam>
                </div>

                <div class="w3-secton">
                  <%= label_tag :description %>
                  <spam class="w3-input"><%= text_area_tag 'product[description]' %></spam>

                </div>
                <div class="w3-secton">
                  <%= label_tag :price %>
                  <spam class="w3-input"><%= text_field_tag 'product[price]' %></spam>
                </div>
                <div class="w3-secton">
                  <%= label_tag :make %>
                  <spam class="w3-input"><%= text_field_tag 'product[make]' %></spam>
                </div>
                <spam class="w3-button w3-right w3-theme w3-hover-teal"><%= submit_tag %></spam>
            </div>
          <% end %>
        </div>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td class="w3-large w3-border-teal "><%= link_to "Back to categories listing", categories_path %> | </td>
        <% if logged_in? && current_user.admin? %>
        <td class="w3-large w3-border-teal "><%= link_to "Edit this category", edit_category_path(@category) %> | </td>
        <td class="w3-large w3-border-teal "><%= link_to 'Destroy',category_path(@category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
   </tbody>
</table>
<br>

app/views/layouts/_footer.html.erb
<footer class="w3-container w3-padding-32 w3-theme-d1 w3-center footer">
  
  <h4>Follow Us</h4>
  <a class="w3-button w3-large w3-teal" href="javascript:void(0)" title="Facebook"><i class="fa fa-facebook"></i></a>
  <a class="w3-button w3-large w3-teal" href="javascript:void(0)" title="Twitter"><i class="fa fa-twitter"></i></a>
  <a class="w3-button w3-large w3-teal" href="javascript:void(0)" title="Google +"><i class="fa fa-google-plus"></i></a>
  <a class="w3-button w3-large w3-teal" href="javascript:void(0)" title="Google +"><i class="fa fa-instagram"></i></a>
  <a class="w3-button w3-large w3-teal w3-hide-small" href="javascript:void(0)" title="Linkedin"><i class="fa fa-linkedin"></i></a>
  <p>Powered by <a href="#" >Prachi Kwatra</a></p>

</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<body id="myPage">

<div class="w3-top">
    <div class="w3-bar w3-theme-d2 w3-left-align">
      <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-white w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
      <span class="w3-bar-item w3-teal"><i class="fa fa-home w3-margin-right"></i><%= link_to 'CamShop', root_path %></span>
      <%= link_to 'About Us', root_path, class: "w3-bar-item w3-button w3-hide-small w3-hover-white w3-text-white" %>
      <a href="#footer" class="w3-bar-item w3-button w3-hide-small w3-hover-white  w3-text-white">Contact Us</a>
        <% if logged_in? %>
          <div class="w3-dropdown-hover w3-hide-small">
          <button class="w3-button w3-hover-white" title="Notifications">Explore our products <i class="fa fa-caret-down"></i></button>  
            <div class="w3-dropdown-content w3-card-4 w3-bar-block">
                <%= link_to "All Company's", categories_path, class: "w3-bar-item w3-button w3-hover-teal" %>
                <%= link_to 'Products', products_path, class: "w3-bar-item w3-button w3-hover-teal" %>
                <%= link_to 'View your Cart', cart_path, class: "w3-bar-item w3-button w3-hover-teal" %>
            </div> 
          </div>
          <div class="w3-dropdown-hover w3-hide-small">
          <button class="w3-button w3-hover-white" title="Notifications">Settings <i class="fa fa-caret-down"></i></button>  
            <div class="w3-dropdown-content w3-card-4 w3-bar-block">
                <%= link_to 'Edit your profile', edit_user_path(current_user), class: "w3-bar-item w3-button w3-hover-teal" %>
                <%= link_to 'View your profile', user_path(current_user), class: "w3-bar-item w3-button w3-hover-teal" %>
                <% if current_user.admin? %>
                  <%= link_to 'Create Category/Company', new_category_path, class: "w3-bar-item w3-button w3-hover-teal" %>
                  <%= link_to 'View all users', users_path, class: "w3-bar-item w3-button w3-hover-teal" %>
                  <%= link_to 'Add new user', signup_path, class: "w3-bar-item w3-button w3-hover-teal" %>
                <% end %>
            </div> 
          </div>
        <% end %>
        
        <div class="w3-dropdown-hover w3-hide-small">
          <button class="w3-button w3-hover-white" title="Notifications">Get Started <i class="fa fa-caret-down"></i></button>     
          <div class="w3-dropdown-content w3-card-4 w3-bar-block">
            <% if logged_in? %>
              <%= link_to 'Log Out', logout_path, method: :delete, class: "w3-bar-item w3-button w3-hover-teal" %>
            <% else %>
              <%= link_to 'Log In', login_path, class: "w3-bar-item w3-button w3-hover-teal" %>
              <%= link_to 'Sign Up', signup_path, class: "w3-bar-item w3-button w3-hover-teal" %>
            <% end %>
          </div> 
        </div>
        <a href="#" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-teal" title="Search"><i class="fa fa-search"></i></a>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CamShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <div class="w3-container w3-padding-32 w3-theme-l5" id="contact">
      <div class="w3-row">
        <div class="w3-col m5">
         <%= render 'layouts/messages' %>
        </div>
      </div>
    </div>
    
    
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/products/index.html.erb
<h1 align="center">Welcome!!!</h1>

<h2 align="center">Listing All products</h2>

<% @products.each do |product| %>

  <div class="w3-container w3-padding-32 w3-theme-l5 w3-center" id="contact">
    <div class="w3-row">
      <h3 align="center"><span class="w3-xlarge w3-border-teal w3-bottombar">Company name: <%= product.name %></span></h3>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Feature: <%= product.description %></p>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Model: <%= product.price %></p>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Model: <%= product.make %></p>
      <% product.save %>
      <%= link_to 'Buy Now', cart_path, class: "w3-button w3-center w3-theme w3-hover-teal w3-medium w3-theme btn w3-bar-item w3-text-white",
                   data: { confirm: 'Are you sure?' } %>   </div> 
  </div>


<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
   <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@user.errors.count, "error") %>
            prohibited this category from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul> 
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

  <%= form_for @user do |f| %>
  <div class="w3-container w3-card-4 w3-padding-16 w3-white form">
      <div class="w3-secton">      
        <%= f.label :username %>
        <%= f.text_field :username, class: "w3-input" %>
      </div>
     
      <div class="w3-secton">      
        <%= f.label :email %>
        <%= f.email_field :email, class: "w3-input" %>
      </div>
      <div class="w3-secton">      
        <%= f.label :password %>
        <%= f.password_field :password, class: "w3-input" %>
      </div>
      <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: 'w3-button w3-right w3-theme w3-hover-teal') %>
      
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="w3-container w3-padding-32 w3-theme-l5" id="contact">
  <div class="w3-row">
    <div class="w3-col m5">
      <div class="w3-padding-16"><h3><span class="w3-xlarge w3-border-teal w3-bottombar">Edit your account</span></h3></i></div>
       <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1 align="center">Welcome!!!</h1>

<h2 align="center">Listing All Users</h2>

<% @users.each do |user| %>

  <div class="w3-container w3-padding-32 w3-theme-l5 w3-center" id="contact">
    <div class="w3-row">
      <h3 align="center"><span class="w3-xlarge w3-border-teal w3-bottombar">User: <%= user.username %></span></h3>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Email-id: <%= user.email %></p>
      <% user.save %>
     </div> 
  </div>


<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    
      <tr>
        <td class="w3-large w3-border-teal "><%= link_to 'Show', user_path(user) %> |</td> 
        <td class="w3-large w3-border-teal "><%= link_to 'Edit', edit_user_path(user) %> |</td> 
        <td class="w3-large w3-border-teal "><%= link_to 'Destroy',user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    
   </tbody>
</table>
<br>
  <% end %>

app/views/users/new.html.erb
<div class="w3-container w3-padding-32 w3-theme-l5" id="contact">
  <div class="w3-row">
    <div class="w3-col m5">
      <div class="w3-padding-16"><h3><span class="w3-xlarge w3-border-teal w3-bottombar">Signup for CamShop App</span></h3></i></div>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<h1 align="center">Welcome <%= @user.username %></h1>

<div class="w3-container w3-padding-32 w3-theme-l5 w3-center" id="contact">
    <div class="w3-row">
      <h3 align="center"><span class="w3-xlarge w3-border-teal w3-bottombar">User: <%= @user.username %></span></h3>
      <p><i class="fa fa-stop-circle-o w3-text-teal w3-xlarge"></i> Email-id: <%= @user.email %></p>
     </div> 
  </div>

  

app/views/welcome/about.html.erb
<h1>This is the about page!!!</h1>
<%= link_to 'Home', root_path %>

app/views/welcome/cart.html.erb
<h1>Welcome to your cart</h1>

app/views/welcome/home.html.erb
<div class="w3-display-container w3-animate-opacity">
  <%= image_tag 'img5.jpg', class: "image"%>
  <div class="w3-container w3-display-bottomleft w3-margin-bottom">  
    
      <%= link_to 'ShOp MoRe SaVe MoRe', categories_path, class: "w3-button w3-xlarge w3-theme w3-hover-teal btn w3-bar-item w3-text-white" %> 
      
  </div>
</div>


<div class="w3-row-padding w3-padding-64 w3-white" id="work">
  <h2>Our Work</h2>
  <p>We Make the deals for the categories that SAVES your DAY and your MONEY.</p>
  
</div>